### ISSUE TITLE
Mettre en place les headers de sécurité

### ISSUE THREAD

**Issue by mlbiche** [inclusion-numerique/mon-suivi-social#20]
cf. https://gitlab.com/incubateur-territoires/startups/monsuivisocial/monsuivisocial-app/-/issues/204

> Suite à la formation beta.gouv au sujet de la cyber-sécu suivie aujourd'hui, il faut rajouter les politiques de sécurité dans les headers :
> - [ ] Content-Security-Policy
> - [x] X-Frame-Options
> - [x] Strict-Transport-Security
> - [x] X-Content-Type-Options
> - [ ] Referrer Policy
>   - [ ] Supprimer les `rel="noopenner noreferrer"` sur les liens

Une bonne partie de ces _headers_ a déjà été implémentée. Par contre, des précisions ont été apportées sur le _header_ `Referrer Policy` et son lien avec l'attribut `rel="noopenner noreferrer"` sur une [conversation Mattermost](https://mattermost.incubateur.net/betagouv/pl/ixfbazg6i7dducnqm5oxhoecpe) de beta.gouv.

**Comment by hugues-m** [comment]
@mlbiche si tu veux t'y essayer, les headers sont à configurer dans le fichier https://github.com/inclusion-numerique/mon-suivi-social/blob/dev/apps/web/src/middleware.ts qui par convention Next.js s'execute à chaque requête.

Pour les liens avec noopenner et ou noreferrer, il faudrait dans le cadre de cette issue rendre les règles eslint compatible (car pour le moment c'est un lint fail si noreferrer n'est pas present)
