### ISSUE TITLE
L'application ne fonctionne pas avec le rôle Responsable de structure

### ISSUE THREAD

**Issue by mlbiche** [inclusion-numerique/mon-suivi-social#25]
Lorsqu'un utilisateur avec le rôle **Responsable de structure** accède à l'application, plusieurs erreurs sont affichées.

* Erreur 500 sur `/beneficiaires`
* Erreur 404 sur `/accompagnements`

_[À compléter...]_

**Comment by hugues-m** [comment]
Comprendre pourquoi les erreurs sont pas claires

**Comment by mlbiche** [comment]
On est bon sur ce ticket, @tglatt a corrigé ce qu'il faut.

Sur ton commentaire @hugues-m, tu es bon aussi non, c'est les derniers changements du _.env.dist_ que tu as fait ?

**Comment by mlbiche** [comment]
@hugues-m Je ferme cette tâche. Je te laisse la rouvrir si tu as besoin pour les variables d'environnement ? 🙂
